apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      name: minio
  replicas: 1
  template:
    metadata:
      labels:
        name: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2022-08-13T21-54-44Z@sha256:998d6f9442174df4e1b4e4c5421ebaf7e8e77e59208928dfea5f974f9b7bda61
          args:
            - gateway
            - s3
            - http://10.128.242.92:31813
          # Below option allows for fixed console port but for some reason login to minio console works. Commented for now
          #  - --console-address
          #  - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: Minio123
            - name: AWS_ACCESS_KEY
              value: 8T3Z1JKA0KXIYF6BASNG
            - name: AWS_SECRET_KEY
              value: BDnyeCEsU7xFAuCHWc6Z39LIKamD4DCIspqzC4bT
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
          livenessProbe:
            tcpSocket:
              port: 9000
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 10"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minio
              topologyKey: "kubernetes.io/hostname"

---
apiVersion: v1
kind: Service
metadata:
  name: minio-gw-svc
  namespace: minio
spec:
  selector:
    app: minio-gw
  ports:
    - protocol: TCP
      port: 6666
      targetPort: 9000
