apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-my-store-external
  namespace: pf9-storage
  labels:
    app: rook-ceph-rgw
    rook_cluster: pf9-storage
    rook_object_store: ceph-objectstore
spec:
  ports:
  - name: rgw
    nodePort: 31813
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rook-ceph-rgw
    rook_cluster: pf9-storage
    rook_object_store: ceph-objectstore
  sessionAffinity: None
  type: NodePort

