apiVersion: v1
kind: Service
metadata:
  name: pf9-docker-registry-svc
  labels:
    name: pf9-docker-registry
  namespace: docker-registry
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007
  selector:
    name: pf9-docker-registry