apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: docker-registry
data:
  config.yml: |
    version: 0.1
    log:
      accesslog:
        disabled: true
    #  level: debug
      formatter: text
    #loglevel: debug # deprecated: use "log"
    storage:
      s3goamz:
        accesskey: __ACCESS_KEY__
        secretkey: __SECRET_KEY__
        region: ceph
        regionendpoint: http://10.128.242.92:31813
        bucket: docker-registry-data
        secure: false
        rootdirectory: /registry
    http:
      addr: 0.0.0.0:5000
      debug:
        addr: localhost:5002
      headers:
        X-Content-Type-Options: [nosniff]